Make control UIControl subclass instead of UIView (close #18)
Onix-Systems/RainyRefreshControl pull request #20
Opened 2016-12-25 18:09 UTC by onix-dolzhenko

2016-12-26 12:50 UTC, derpoliuk requested changes

2016-12-26 12:50 UTC, derpoliuk commented on RainyRefresh/ONXRefreshControl.swift
> +        if let superview = superview as? UIScrollView, !refreshing {
It's better to use `guard` here.

2016-12-26 12:50 UTC, derpoliuk commented on RainyRefresh/ONXRefreshControl.swift
> +        if let superview = superview as? UIScrollView, refreshing {
It's better to use `guard` here.

2016-12-26 12:50 UTC, derpoliuk commented on RainyRefresh/ONXRefreshControl.swift
> +        if let superview = superview as? UIScrollView, !changingInset {
It's better to use `guard` here.

2016-12-26 12:50 UTC, derpoliuk commented on RainyRefresh/ONXRefreshControl.swift
> +    private func commonInit() {
Let's get rid of `commonInit` and `setup` methods and leave this logic to subclasses. Reason - it is just adds boilerplate code to this class without any functionality.

2016-12-26 12:50 UTC, derpoliuk commented on RainyRefresh/RainyRefreshControl.swift
> +        //        if let scene = GameScene.unarchiveFromFile("GameScene") as? GameScene {
Do we need this?

2016-12-26 12:50 UTC, derpoliuk commented on RainyRefresh/ONXRefreshControl.swift
> +    public var animationDuration = TimeInterval(0.33)
Do we need make those properties `public`?

2016-12-26 12:53 UTC, onix-dolzhenko commented on RainyRefresh/RainyRefreshControl.swift
> +        //        if let scene = GameScene.unarchiveFromFile("GameScene") as? GameScene {
removed

2016-12-26 12:55 UTC, onix-dolzhenko commented on RainyRefresh/ONXRefreshControl.swift
> +        if let superview = superview as? UIScrollView, !changingInset {
changed

2016-12-26 12:55 UTC, onix-dolzhenko commented on RainyRefresh/ONXRefreshControl.swift
> +        if let superview = superview as? UIScrollView, refreshing {
changed

2016-12-26 12:56 UTC, onix-dolzhenko commented on RainyRefresh/ONXRefreshControl.swift
> +        if let superview = superview as? UIScrollView, !refreshing {
changed

2016-12-26 13:07 UTC, onix-dolzhenko commented on RainyRefresh/ONXRefreshControl.swift
> +    private func commonInit() {
what about just to leave setup and place it instead of ```commonInit``` ?

2016-12-28 09:31 UTC, derpoliuk approved these changes

2016-12-28 09:31 UTC, derpoliuk commented
Great, thank you! Merging.

2016-12-28 09:31 UTC, merged